package org.lilachshop.panels;

import java.io.Serializable;

public enum PanelEnum implements Serializable {
    CUSTOMER_ANONYMOUS, STORE_CUSTOMER, CHAIN_CUSTOMER, ANNUAL_CUSTOMER, EMPLOYEE_ANONYMOUS, GENERAL_EMPLOYEE, STORE_MANAGER, CHAIN_MANAGER, CUSTOMER_SERVICE, SYSTEM_MANAGER
}
